baseURL = "https://www.earthtophilosophy.com/"
languageCode = "en-us"
title = "Earth to Philosophy"
theme = "castanet"

[params]
copyright_notice = "© 2018 Andrea Gammon and Claire Hamlett"
description = "An Environmental Philosophy Podcast"
media_prefix = "/"
site_theme = "blue"
enable_jumbo = "true"
site_layout = "grid"

[params.feed]
copyright = "© 2018 Andrea Gammon and Claire Hamlett"
itunes_author = "Andrea Gammon and Claire Hamlett"
itunes_summary = "An Environmental Philosophy Podcast"
itunes_owner_name = "Andrea Gammon"
itunes_owner_email = "example@example.org"
itunes_image = "https://www.earthtophilosophy.com/img/logo.png"
itunes_top_category = "Technology"

[params.social]
twitter_domain = "earthtophilosophy.com"

[params.authors]
  [params.authors.Andrea]
    name = "Andrea Gammon"
    thumbnail = "/img/host/agammon.jpg"
    bio = ""

  [params.authors.Claire]
    name = "Claire Hamlett"
    thumbnail = "/img/host/chamlett.jpg"
    bio = ""

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"

[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"
