[context.production.environment]
  HUGO_VERSION = "0.52"
  
[[redirects]]
  from = "/"
  to = "/earth-to-philosophy/"
  status = 200
  force = true
  
[[redirects]]
  from = "/earth-to-philosophy/*"
  to = "https://shows.acast.com/earth-to-philosophy/:splat"
  status = 200
