[context.production.environment]
  HUGO_VERSION = "0.52"
  
[[redirects]]
  from = "/"
  to = "/earth-to-philosophy/"
  status = 302
  force = true
  
[[redirects]]
  from = "/*"
  to = "https://shows.acast.com/:splat"
  status = 200
