baseURL = "http://example.org/"
languageCode = "en-us"
title = "🌍 Earth to Philosophy"
theme = "castanet"

[params]
copyright_notice = "Copyright 2018 Andrea Gammon and Claire Hamlett"
description = "An Environmental Philosophy Podcast"
media_prefix = "http://example.org/"
site_theme = "blue"
enable_jumbo = "true"
site_layout = "grid"

[params.feed]
copyright = "Copyright 2018 Andrea Gammon and Claire Hamlett"
itunes_author = "Andrea Gammon and Claire Hamlett"
itunes_summary = "An Environmental Philosophy Podcast"
itunes_owner_name = "Andrea Gammon"
itunes_owner_email = "example@example.org"
itunes_image = ""
itunes_top_category = "Technology"

[params.social]
twitter_domain = "earthtophilosophy.com"

[params.authors]
  [params.authors.andrea]
    name = "Andrea Gammon"
    thumbnail = ""
    bio = "They don't call me Dr. Gammon for nothing!"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"

[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "books"
    parent = "resources"

[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "books"
    parent = "resources"
